apiVersion: apps/v1
kind: Deployment
metadata:
  name: marriage-images
  namespace: prod
  labels:
    app: marriage-images
spec:
  replicas: 3
  selector:
    matchLabels:
      app: marriage-images
  template:
    metadata:
      labels:
        app: marriage-images
    spec:
      containers:
        - name: marriage-images
          image: mrvanosh/marriage-images:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 3072Mi
              cpu: 4000m
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: marriage-images-config
                  key: NODE_ENV
            - name: R2_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: marriage-images-config
                  key: R2_BUCKET_NAME
            - name: R2_PUBLIC_URL
              valueFrom:
                configMapKeyRef:
                  name: marriage-images-config
                  key: R2_PUBLIC_URL
            - name: NEXT_PUBLIC_APP_URL
              valueFrom:
                configMapKeyRef:
                  name: marriage-images-config
                  key: NEXT_PUBLIC_APP_URL
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: marriage-images-secret
                  key: DATABASE_URL
            - name: R2_ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: marriage-images-secret
                  key: R2_ACCOUNT_ID
            - name: R2_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: marriage-images-secret
                  key: R2_ACCESS_KEY_ID
            - name: R2_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: marriage-images-secret
                  key: R2_SECRET_ACCESS_KEY
            - name: LOGTAIL_SOURCE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: marriage-images-secret
                  key: LOGTAIL_SOURCE_TOKEN
                  optional: true
            - name: NEXT_PUBLIC_POSTHOG_KEY
              valueFrom:
                secretKeyRef:
                  name: marriage-images-secret
                  key: NEXT_PUBLIC_POSTHOG_KEY
                  optional: true
            - name: NEXT_PUBLIC_POSTHOG_HOST
              valueFrom:
                secretKeyRef:
                  name: marriage-images-secret
                  key: NEXT_PUBLIC_POSTHOG_HOST
                  optional: true
          volumeMounts:
            - name: uploads
              mountPath: /app/public/uploads
      volumes:
        - name: uploads
          emptyDir: {}
      # Optional: If you need to pull from a private registry
      # imagePullSecrets:
      # - name: registry-secret
