apiVersion: v1
kind: Secret
metadata:
  name: marriage-images-secret
  namespace: prod
type: Opaque
stringData:
  # Database connection
  DATABASE_URL: 'mysql://marriage:marriage@192.168.42.100:3306/marriage'

  # Cloudflare R2 credentials
  R2_ACCOUNT_ID: 62ee7c0bb562d876a7cc6e8f9f751166
  R2_ACCESS_KEY_ID: cf1c46dd494cb8d019af0af3d6c052ff
  R2_SECRET_ACCESS_KEY: da0ce005a28b6775a5d95bf1a3fa338e9b4a21d9294b1a48cf7c3f122d897a93

  # Optional: Logging with Better Stack
  LOGTAIL_SOURCE_TOKEN: ''

  # Optional: Analytics with PostHog
  NEXT_PUBLIC_POSTHOG_KEY: ''
  NEXT_PUBLIC_POSTHOG_HOST: 'https://app.posthog.com'
